# FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: '%env(SENDER_ADDRESS)%'
        sender_name: My Suit
    registration:
        form:
            type: App\Form\RegistrationType