framework:
    default_locale: fr
    secret: '%env(APP_SECRET)%'
    esi: { enabled: true }
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
       engines: ['twig']
    trusted_hosts: ~
    session:
       handler_id: session.handler.native_file
       save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
       cookie_domain: '%env(COOKIES_DOMAIN)%'
    fragments: ~
    http_method_override: true
    php_errors:
       log: true
    assets:
       json_manifest_path: '%kernel.root_dir%/../public/build/manifest.json'